# Generated by Django 2.2 on 2021-05-25 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quanhuyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquanhuyen', models.CharField(max_length=10)),
                ('tenquanhuyen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tinhthanh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matinhthanh', models.CharField(max_length=10)),
                ('tentinhthanh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Xaphuong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxaphuong', models.CharField(max_length=10)),
                ('tenxaphuong', models.CharField(max_length=100)),
                ('quanhuyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Quanhuyen')),
            ],
        ),
        migrations.AddField(
            model_name='quanhuyen',
            name='tinhthanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Tinhthanh'),
        ),
    ]
