# Generated by Django 2.2 on 2021-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benhnhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('1', 'Nam'), ('0', 'Nữ')], default='', max_length=10)),
                ('ngaysinh', models.DateField()),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('mabaohiem', models.CharField(default='', max_length=15)),
                ('bhyt_ngaycap', models.DateField()),
                ('bhyt_sudungtu', models.DateField()),
                ('bhyt_sudungden', models.DateField()),
                ('macongdan', models.CharField(default='', max_length=15)),
                ('nguoilienhe', models.CharField(max_length=255)),
                ('sdt_nguoilienhe', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Quanlybenhnhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
