# Generated by Django 2.2 on 2021-05-25 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('patient', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quanlybenhnhan',
            name='bacsi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Bacsi'),
        ),
        migrations.AddField(
            model_name='quanlybenhnhan',
            name='benhnhan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Benhnhan'),
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='donviyte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Donviyte'),
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='quanhuyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Quanhuyen'),
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='tinhthanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Tinhthanh'),
        ),
        migrations.AddField(
            model_name='benhnhan',
            name='xaphuong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Xaphuong'),
        ),
    ]
