# Generated by Django 2.2 on 2021-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donviyte',
            name='trangthaidonvi',
            field=models.BooleanField(choices=[('1', 'Hoạt động'), ('0', 'Không hoạt động')], default='0', null=True),
        ),
    ]
