# Generated by Django 2.2 on 2021-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210525_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donviyte',
            name='trangthaidonvi',
            field=models.CharField(choices=[('1', 'Hoạt động'), ('0', 'Không hoạt động')], default='0', max_length=20, null=True),
        ),
    ]
