# Generated by Django 2.2 on 2021-05-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210525_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donviyte',
            name='quanhuyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Quanhuyen'),
        ),
        migrations.AlterField(
            model_name='donviyte',
            name='tinhthanh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Tinhthanh'),
        ),
        migrations.AlterField(
            model_name='donviyte',
            name='trangthaidonvi',
            field=models.CharField(choices=[('1', 'Hoạt động'), ('0', 'Không hoạt động')], default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donviyte',
            name='xaphuong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Xaphuong'),
        ),
    ]
