# Generated by Django 2.2 on 2021-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210526_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donviyte',
            name='trangthaidonvi',
            field=models.CharField(choices=[('Hoạt động', 'Hoạt động'), ('Không hoạt động', 'Không hoạt động')], default='', max_length=20, null=True),
        ),
    ]
